In [3]:
import numpy as np
from util.lab_utils_common import sigmoid
X = np.array([200, 17])
W = np.array([[1, -3, 5],
              [-2, 4, -6]])
b = np.array([-1, 1, 2])

print(X)
print(W)
print(b)

[200  17]
[[ 1 -3  5]
 [-2  4 -6]]
[-1  1  2]


In [4]:
def dense(a_in, W, b):
    units = W.shape[1]
    a_out = np.zeros(units)
    for j in range(units):
        w = W[:,j]
        z = np.dot(w, a_in) +b[j]
        a_out[j] = sigmoid(z)
        print(f"W: {w}")
    print(units, a_out)
    return a_out

print(dense(X, W, b))

W: [ 1 -2]
W: [-3  4]
W: [ 5 -6]
3 [1.00e+000 7.12e-218 1.00e+000]
[1.00e+000 7.12e-218 1.00e+000]


In [16]:
def dense(A_in, W, B):
    z = np.matmul(A_in, W) + B
    a_out = sigmoid(z)
    return a_out

print(f"A_out: {dense(X, W, b)}")

A_out: [1.00e+000 7.12e-218 1.00e+000]
